config/routes.rb
Rails.application.routes.draw do
    root to: 'employees#new'
    devise_for :employees, :controllers => { :registrations => "employees" }
    get 'system_access_request_external_action', to: 'system_access_requests#external_action'
    resources :system_access_requests
    resources :employees, only: [:index]
    resources :employees do
        get 'pending_system_access_requests', to: 'system_access_requests#pending'
        get 'not_pending_system_access_requests', to: 'system_access_requests#not_pending'
    end
    resources :resources
end

app/models/system_access_request.rb
class SystemAccessRequest < ApplicationRecord
    include ParamMassageUtilities
    belongs_to :employee, optional: true
    has_many :system_access_request_departments
    has_many :departments, through: :system_access_request_departments
    has_many :system_access_request_groups
    has_many :groups, through: :system_access_request_groups
    has_many :system_access_request_softwares
    has_many :softwares, through: :system_access_request_softwares
    has_many :system_access_request_system_access_fields
    has_many :system_access_fields, through: :system_access_request_system_access_fields
    has_many :signatures, dependent: :destroy
    has_one :external_action_authorization
    accepts_nested_attributes_for :signatures

    enum state: [:pending, :rejected, :approved]

    REASONS = ['new', 'change', 'termination'].freeze.map(&:freeze)

    class << self
        def create_new_system_access!(attributes, employee)
            system_access_request = SystemAccessRequest.new
            system_access_request.effective_date = SystemAccessRequest.format_date(attributes, "effective_date".freeze)
            system_access_request.reason = attributes['reason']
            system_access_request.privileged_access = attributes['privileged_access']
            system_access_request.business_justification = attributes['business_justification']
            system_access_request.special_instructions = attributes['special_instructions']
            system_access_request.other_access = attributes['other_access']
            system_access_request.sales_rep_email = attributes['sales_rep_email']
            employee.system_access_requests << system_access_request
            employee.save!(validate: false)
            system_access_request.save!
            system_access_request.pending!
            system_access_request
        end

        def select_all_state_and_submitter_id(state, submitter_id)
            state_and_submitter_query = <<-SQL
                SELECT e.id AS employee_id, CONCAT(e.first_name, ' ', e.last_name) AS full_name, e.job_title,
                       sar.effective_date, sar.reason, sar.state, sar.id AS system_access_request_id
                FROM employees e
                INNER JOIN system_access_requests sar ON sar.employee_id = e.id
                INNER JOIN signatures sig ON sig.system_access_request_id = sar.id
                WHERE
                    sar.state IN (#{[*state].join(',')})
                AND
                    sig.submitter_id = #{submitter_id}
                GROUP BY e.id, sar.id
            SQL
            ActiveRecord::Base.connection.select_all(state_and_submitter_query)
        end

        def check_external_action(action_to_try)
            return nil unless self.allowed_external_actions.include?(action_to_try)
            action_to_try
        end

        def allowed_external_actions
            self.states.keys - ["pending"]
        end
    end

    def create_association!(association, association_class, assoc_ids)
            assoc_ids.each do | assoc_id |
            assoc_obj = association_class.new
            assoc_obj.system_access_request_id = self.id
            assoc_obj.send("#{association}_id=".to_sym, assoc_id)
            assoc_obj.save!
            assoc_obj
        end
    end

    def manager_signatures
        self.signatures.where(signature_type: "supervisor_manager")
    end

    def change_state_and_use_external_action(action_to_perform)
        self.state = action_to_perform
        self.save!
        self.external_action_authorization.used!
    end

    def software_role(software_id)
        SystemAccessRequestSoftware.find_by_software_id_and_system_access_request_id(software_id, self.id).role rescue nil
    end

    def external_action_auth_code
        self.external_action_authorization.authorization_code
    end

    def construct_external_action_url(action)
        "system_access_request_external_action?sar_id=#{self.id}&sar_action=#{action}&authorization_code=#{self.external_action_auth_code}"
    end

    def external_response_json
        {
            employee_name: self.employee.full_name,
            reason: self.reason,
            current_status: self.state

        }.to_json
    end

end

app/controllers/system_access_requests_controller.rb
class SystemAccessRequestsController < ApplicationController
    skip_before_action :authenticate_employee!, :only => [:external_action]

    def index
        @system_access_requests = SystemAccessRequest.includes(:employee).all
    end

    def update
       sar = SystemAccessRequest.find(system_access_request_params[:id]).send("#{system_access_request_params[:state]}!")
       render json: sar
    end

    def pending
        @pending_sars = SystemAccessRequest.select_all_state_and_submitter_id(SystemAccessRequest.states[:pending], current_employee.id)
    end

    def not_pending
        @not_pending_sars = SystemAccessRequest.select_all_state_and_submitter_id(
            [SystemAccessRequest.states[:rejected], SystemAccessRequest.states[:approved]],
            current_employee.id
        )
    end

    def external_action
        unless ExternalActionAuthorization.where(authorization_code: params[:authorization_code]).first.nil?
            if (action_to_perform = SystemAccessRequest.check_external_action(params[:sar_action]))
                sar = SystemAccessRequest.where(id: params[:sar_id]).first
                return render json: invalid_response(sar) if invalid_request?(sar)
                sar.change_state_and_use_external_action(action_to_perform)
                return render json: sar.external_response_json
            end
            render json: { failure: "#{params[:sar_action].titlecase} action is not in the allowed action list" }
        end
        render json: { failure: ExternalActionAuthorization::EXTERNAL_ACTION_AUTHORIZATION_REJECTIONS[:no_sar] }
    end

    private
        def invalid_request?(sar)
            sar.nil? || sar.external_action_authorization.used?
        end

        def invalid_response(sar)
            {
                failure:
                ExternalActionAuthorization::EXTERNAL_ACTION_AUTHORIZATION_REJECTIONS[ExternalActionAuthorization.
                    detect_invalid_external_action_reason(sar)]
            }.to_json
        end

        def system_access_request_params
            params.require(:system_access_request).permit(:id, :state)
        end

end

app/views/system_access_requests/shared/_system_access_requests_state_table.html.erb
<div class="card">
    <div class="card-content">
        <h5 style="float:left"><%= caption %> Requests</h5>
        <table id="sar-table" class="highlight">
            <thead>
                <tr>
                    <th>Full Name</th>
                    <th>Job Title</th>
                    <th>Reason For Request</th>
                    <th>Effective Date</th>
                    <th>Current Status</th>
                    <% if current_employee.admin? && action == :pending %>
                        <%= render partial: 'system_access_requests/shared/system_access_requests_state_table_admin_actions_header' %>
                    <% end %>
                </tr>
            </thead>
            <tbody>
                <% sars.each do | sar | %>
                    <tr>
                        <td><%= link_to(sar['full_name'], employee_path(sar['employee_id'])) %></td>
                        <td><%= sar['job_title'] %></td>
                        <td> This is a <span style='text-decoration:underline;'><%= sar['reason']%></span> user.</td>
                        <td><%= sar['effective_date'] %></td>
                        <td><%= SystemAccessRequest.states.key(sar['state']).capitalize %></td>
                        <% if current_employee.admin? && action == :pending  %>
                            <%= render partial: 'system_access_requests/shared/system_access_requests_state_table_admin_actions_body',
                                    locals: { sar: sar }
                            %>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/system_access_requests/shared/_system_access_requests_state_table_admin_actions_body.html.erb
<td>
    <a href="#" id="approve-sar" data-sar-id="<%= sar['system_access_request_id'] %>">
        <i class="material-icons" style="font-size:35px;color:green;">add_circle</i>
    </a>
</td>
<td>
    <a href="#" id="reject-sar" data-sar-id="<%= sar['system_access_request_id'] %>">
        <i class="material-icons" style="font-size:35px;color:red;">remove_circle</i>
    </a>
</td>

app/views/system_access_requests/shared/_system_access_requests_state_table_admin_actions_header.html.erb
<th>Approve</th>
<th>Reject</th>