config/routes.rb
Rails.application.routes.draw do
    root to: 'employees#new'
    devise_for :employees, :controllers => { :registrations => "employees" }
    get 'system_access_request_external_action', to: 'system_access_requests#external_action'
    resources :system_access_requests
    resources :employees, only: [:index]
    resources :employees do
        get 'pending_system_access_requests', to: 'system_access_requests#pending'
        get 'not_pending_system_access_requests', to: 'system_access_requests#not_pending'
    end
    resources :resources
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :system_access_requests, dependent: :destroy
    accepts_nested_attributes_for :system_access_requests
    validates :email, uniqueness: true
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable, :timeoutable

    after_create :assign_default_role

    enum role:  {
        admin: 1,
        manager: 2,
        sales_rep: 3,
        standard: 4
    }

    class << self
        def create_new_employee!(attributes)
            employee = Employee.new
            employee.employee = attributes['employee']
            employee.email = attributes['email']
            employee.first_name = attributes['first_name']
            employee.middle_initial = attributes['middle_initial']
            employee.last_name = attributes['last_name']
            employee.job_title = attributes['job_title']
            employee.save!(validate: false)
            employee
        end
    end


    def full_name
        [first_name, middle_initial, last_name].compact.reject(&:blank?).join(' ')
    end


    private

        def assign_default_role
            self.role = "standard" if self.role.to_s.empty?
            self.save(validate: false)
        end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    include ParamMassageUtilities
    before_action :set_employee, only: [:show, :edit, :update, :destroy]

    # GET /employees
    # GET /employees.json
    def index
        @employees = Employee.all
    end

    # GET /employees/1
    # GET /employees/1.json
    def show
    end

    # GET /employees/new
    def new
        @employee = Employee.new
        @system_access_request = @employee.system_access_requests.build
    end

    # GET /employees/1/edit
    def edit
    end

    # POST /employees
    # POST /employees.json
    def create
        #raise employee_params.inspect
        Employee.transaction do
            #so we are either going to add it to an existing employee or create a new one
            @employee = Employee.find_by_email(employee_params[:email])
            @employee = Employee.create_new_employee!(employee_params) if @employee.nil?
            raise ActiveRecord::Rollback unless SystemAccessRequest.transaction(requires_new: true) do
                system_access_requests_params = employee_params[:system_access_requests_attributes]["0"]
                system_access_request = SystemAccessRequest.create_new_system_access!(system_access_requests_params, @employee)
                ['group', 'system_access_field', 'department'].each do | association |
                    association_class = Object.const_get("SystemAccessRequest#{association.titlecase.delete(' ')}")
                    raise ActiveRecord::Rollback unless association_class.transaction(requires_new: true) do
                        assoc_ids = system_access_requests_params["#{association}_ids"].reject(&:blank?)
                        system_access_request.create_association!(association, association_class, assoc_ids)
                    end
                end
                departments = system_access_requests_params[:departments]["11"] rescue nil
                unless departments.nil?
                    sard_assoc = SystemAccessRequestDepartment.find_by_department_id(11)
                    sard_assoc.other_text = departments["other_text"]
                    sard_assoc.save!
                end
                # populate all of the softwares and their roles
                Software.first.id.upto(Software.last.id).each do | index |
                    software = system_access_requests_params[:softwares][index.to_s]
                    # if they didnt' select a role then they cannot have the software
                    # this is validated on the front end.
                    next if software[:roles][:role_ids].to_s.empty?
                    raise ActiveRecord::Rollback unless SystemAccessRequestSoftware.transaction(requires_new: true) do
                        SystemAccessRequestSoftware.create!({
                            software_id: software[:id],
                            system_access_request_id: system_access_request.id,
                            role_id: software[:roles][:role_ids]
                        })
                    end
                end
                if Signature.create!(
                    signature_type: 'supervisor_manager',
                    system_access_request_id: system_access_request.id,
                    signature: current_employee.full_name,
                    submitter_id: current_employee.id,
                    date: Date.today
                )
                    SystemAccessRequestRegistration.new(system_access_request, @employee).run
                end
            end
        end

        respond_to do |format|
            unless @employee.id.nil?
                format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
                format.json { render :show, status: :created, location: @employee }
            else
                format.html { render :new }
                format.json { render json: @employee.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /employees/1
    # PATCH/PUT /employees/1.json
    def update
        respond_to do |format|
            if @employee.update(employee_params)
                format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
                format.json { render :show, status: :ok, location: @employee }
            else
                format.html { render :edit }
                format.json { render json: @employee.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /employees/1
    # DELETE /employees/1.json
    def destroy
        @employee.destroy
        respond_to do |format|
            format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_employee
            @employee = Employee.includes({
                system_access_requests: [:groups, :departments, :softwares, :system_access_fields] }).find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def employee_params
            params.require(:employee).permit(
                :employee, :first_name, :last_name, :middle_initial, :job_title, :email,
                {
                    system_access_requests_attributes: [
                                        :effective_date, :reason, :privileged_access, :business_justification,
                                        :special_instructions, :other_access, :sales_rep_email,
                                        {system_access_field_ids: []},
                                        {departments: [:other_text]},
                                        {department_ids: []},
                                        {group_ids: []},
                                        softwares: [:id, roles: [:role_ids]],
                                        signatures_attributes: [
                                            :signature_type, :signature, :date
                                        ]
                                    ]
                }
            )
        end
end

app/helpers/employees_helper.rb
module EmployeesHelper
    def required_field(message='This Field Is Required.')
        "<sup><i class='material-icons tiny required' data-position='top' data-delay='50' data-tooltip='#{message}'>warning</i></sup>"
    end
end

app/views/employees/_form.html.erb
<div class="card teal lighten-5">
    <div class="card-content">
        <%= form_with(model: employee, local: true, html: { id: "system-access-form"}) do | form | %>
            <% if employee.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
                    <ul>
                        <% employee.errors.full_messages.each do | message | %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="card">
                <div class="card-content">
                    <%= render partial: 'employees/shared/employee', locals: { form: form}  %>
                    <%= render partial: 'employees/shared/system_access_request', locals: { form: form}  %>

                    <div class="actions">
                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Request Access
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
        <% end %>
    </div>
</div>

app/views/employees/edit.html.erb
<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Middle initial</th>
      <th>Job title</th>
      <th>Employee email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.middle_initial %></td>
        <td><%= employee.job_title %></td>
        <td><%= employee.email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<div class='card'>
    <div class='card-content'>
        <div class="row">
            <div class="col s12">
                <strong>W2-Employee</strong>
                <%= @employee.employee %>
            </div>
        </div>
        <div class="row">
            <div class="col s3">
              <strong>First name:</strong>
              <%= @employee.first_name %>
            </div>
            <div class="col s3">
              <strong>Middle initial:</strong>
              <%= @employee.middle_initial %>
            </div>
            <div class="col s3">
              <strong>Last name:</strong>
              <%= @employee.last_name %>
            </div>
            <div class="col s3">
                <strong>Job title:</strong>
                <%= @employee.job_title %>
            </div>
        </div>

        <div class="row">
            <div class="col s3">
                <strong>Employee email:</strong>
                <%= @employee.email %>
            </div>
            <% [*@employee.system_access_requests.last].each do | sar | %>
                <div class="col s3">
                    <strong>Effective Date:</strong>
                    <%= sar.effective_date.strftime('%Y-%m-%d') %>
                </div>
                <div class="col s3">
                    <strong>Reason:</strong>
                    <%= sar.reason %>
                </div>
            </div>
            <div class="row">
                <strong class="left">Departments:</strong><br>
                <% sar.departments.each do | dep |  %>
                    <div class="col s3">
                        <%= dep.name %>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <strong class="left">System Access:</strong><br>
                <% sar.system_access_fields.each do | saf |  %>
                    <div class="col s3">
                        <%= saf.name %>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <strong class="left">Softwares:</strong><br>
                <% sar.softwares.each do | soft |  %>
                    <div class="col s3">
                        Software:
                        <%= soft.name %><br>
                        Role:
                        <%= sar.software_role(soft.id).name %>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <strong class="left">Groups:</strong><br>
                <% sar.groups.each_with_index do | group, index |  %>
                    <div class="col s3">
                        Group Type:
                        <%= group.group_type %> <br>
                        Group:
                        <%= group.name %>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <strong class="left">Additional Requests:</strong><br>
                <div class="col s3">
                    <strong>Privileged Access:</strong>
                    <%= sar.privileged_access %>
                </div>
                <div class="col s3">
                    <strong>Business Justification:</strong>
                    <%= sar.business_justification %>
                 </div>
                 <div class="col s3">
                    <strong>Other Access:</strong>
                    <%= sar.other_access %>
                 </div>
                 <div class="col s3">
                    <strong>Special Instructions:</strong>
                    <%= sar.special_instructions %>
                 </div>
            </div>
         <% end %>
    </div>
</div>