config/routes.rb
Rails.application.routes.draw do
    root to: 'employees#new'
    devise_for :employees, :controllers => { :registrations => "employees" }
    get 'system_access_request_external_action', to: 'system_access_requests#external_action'
    resources :system_access_requests
    resources :employees, only: [:index]
    resources :employees do
        get 'pending_system_access_requests', to: 'system_access_requests#pending'
        get 'not_pending_system_access_requests', to: 'system_access_requests#not_pending'
    end
    resources :resources
end

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resource_name %>
  </div>

  <div class="input-field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :resource_url %>
  </div>

  <div class="field">
    <%= form.label :resource_type %>
    <%= form.select(:resource_type, Resource.resource_types.keys) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div class="card">
    <div class="card-content">
        <div class="row">
        <h4>Resources</h4>
            <% @resources.each do |resource| %>
                <div class="col s3">
                    <%= link_to "#{resource.name} <i class='material-icons' style='vertical-align:top;'>open_in_new</i>".html_safe,
                        resource.url, target: "_blank", class: 'btn btn-large waves-effect waves-light teal lighten-2' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<p>
  <strong>Resource type:</strong>
  <%= @resource.resource_type %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>