config/routes.rb
Rails.application.routes.draw do
    root to: 'employees#new'
    devise_for :employees, :controllers => { :registrations => "employees" }
    get 'system_access_request_external_action', to: 'system_access_requests#external_action'
    resources :system_access_requests
    resources :employees, only: [:index]
    resources :employees do
        get 'pending_system_access_requests', to: 'system_access_requests#pending'
        get 'not_pending_system_access_requests', to: 'system_access_requests#not_pending'
    end
    resources :resources
end

app/views/layouts/navigation/_forms_dropdown.html.erb
<ul id="forms-dropdown-menu" class="dropdown-content">
    <li><%= link_to "System Access Request", new_employee_path %></li>
</ul>

app/views/layouts/navigation/_nav.html.erb
<header>
    <nav class="teal lighten-5">
        <div class="nav-wrapper">
            <div class="container">
                <%= image_tag "mdlabs-logo.png", class: "brand-logo" %>
                <% if employee_signed_in? %>
                    <a href="#" data-activates="mobile-demo" class="button-collapse grey-text"><i class="material-icons">menu</i></a>
                    <%= render partial: "layouts/navigation/nav_links", locals: {
                                        mobile_id: "nav-mobile",
                                        drop_down_class: "dropdown-button",
                                        mobile_classes: "right grey-text hide-on-med-and-down"
                    } %>
                    <%= render partial: "layouts/navigation/nav_links", locals: {
                                        mobile_id: "mobile-demo",
                                        drop_down_class: "mobile-dropdown-button",
                                        mobile_classes: "side-nav"
                    } %>
                <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/navigation/_nav_links.html.erb
<ul id="<%= mobile_id %>" class="<%= mobile_classes %>" data-turbolinks="false">
     <li>
        <%= render 'layouts/navigation/forms_dropdown' %>
        <a class="<%= drop_down_class %> grey-text" id="admin-forms"  data-activates="forms-dropdown-menu">
            <% unless mobile_id == "mobile-demo" %>
                <i class="material-icons left">note_add</i>
            <% end %>
            Administrative Forms
            <i class="material-icons right">arrow_drop_down</i>
        </a>
     </li>
     <li>
        <%= render 'layouts/navigation/submitted_request_dropdown' %>
        <a class="<%= drop_down_class %> grey-text" id="submitted-requests" data-activates="requests-dropdown-menu">
            <% unless mobile_id == "mobile-demo" %>
                <i class="material-icons left">list</i>
            <% end %>
                Submitted Requests
            <i class="material-icons right">arrow_drop_down</i>
        </a>
     </li>
     <li>
        <a class="grey-text" id="resource" href="<%= resources_path %>">
           <i class="material-icons left">library_books</i>
           Resources
        </a>
     </li>
     <li>
        <%= link_to "Sign Out <i class='material-icons left'>lock_open</i>".html_safe,
            destroy_employee_session_path, class: "grey-text", method: :delete %>
    </li>
</ul>

app/views/layouts/navigation/_submitted_request_dropdown.html.erb
<ul id="requests-dropdown-menu" class="dropdown-content">
    <li><%= link_to "Pending Requests", employee_pending_system_access_requests_path(employee_id: current_employee.id),
        id: "pending-requests" %></li>
    <li><%= link_to "Not Pending Requests", employee_not_pending_system_access_requests_path(employee_id: current_employee.id),
        id: "not-pending-requests" %></li>
</ul>